# Generated by Django 5.1 on 2024-10-17 09:06

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitflexproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutcategory',
            options={'verbose_name_plural': 'Workout Categories'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='program',
            new_name='workout_program',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
