# Generated by Django 5.1 on 2024-11-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitflexproduct', '0002_alter_workoutcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogram',
            name='image',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to='products/'),
        ),
    ]
