# Generated by Django 5.1 on 2024-11-08 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitflexproduct', '0003_alter_workoutprogram_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_first_name', models.CharField(blank=True, max_length=50)),
                ('default_last_name', models.CharField(blank=True, max_length=50)),
                ('purchased_programs', models.ManyToManyField(blank=True, related_name='purchased_by', to='fitflexproduct.workoutprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlisted_by', to='fitflexproduct.workoutprogram')),
            ],
        ),
    ]
