# Generated by Django 5.1 on 2024-11-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='purchased_programs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wishlist',
        ),
    ]
